"""empty message

Revision ID: de042624875d
Revises: 
Create Date: 2021-12-08 16:54:10.108068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de042624875d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('is_super_user', sa.Boolean(), nullable=True),
    sa.Column('school_logo_name', sa.String(length=200), nullable=True),
    sa.Column('matya_logo_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('general_txt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prnt_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('h_name', sa.String(length=50), nullable=True),
    sa.Column('e_name', sa.String(length=50), nullable=True),
    sa.Column('h_plural_name', sa.String(length=100), nullable=True),
    sa.Column('gt_type', sa.String(length=50), nullable=True),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('color_txt', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('table_color', sa.String(length=50), nullable=True),
    sa.Column('title_color', sa.String(length=50), nullable=True),
    sa.Column('odd_color', sa.String(length=50), nullable=True),
    sa.Column('even_color', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('hide', sa.Boolean(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('usr_node', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Destination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['general_txt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['general_txt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Gt_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['general_txt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['general_txt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('profetional', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['general_txt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Student_email'), 'Student', ['email'], unique=True)
    op.create_index(op.f('ix_Student_last_name'), 'Student', ['last_name'], unique=False)
    op.create_table('Todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['general_txt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_child_relationship',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['general_txt.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['general_txt.id'], )
    )
    op.create_table('std_gt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('gt_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('hide', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['gt_id'], ['general_txt.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['Status.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['Student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('std_gt')
    op.drop_table('parent_child_relationship')
    op.drop_table('Todo')
    op.drop_index(op.f('ix_Student_last_name'), table_name='Student')
    op.drop_index(op.f('ix_Student_email'), table_name='Student')
    op.drop_table('Student')
    op.drop_table('Status')
    op.drop_table('Gt_class')
    op.drop_table('Goal')
    op.drop_table('Destination')
    op.drop_table('general_txt')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
