"""empty message

Revision ID: e1621f887723
Revises: de042624875d
Create Date: 2021-12-08 17:16:02.942250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1621f887723'
down_revision = 'de042624875d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('general_txt_author_id_fkey', 'general_txt', type_='foreignkey')
    op.drop_column('general_txt', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general_txt', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('general_txt_author_id_fkey', 'general_txt', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###
